version: 1.0.{build}

image: Visual Studio 2017

dotnet_csproj:

  patch: true

  file: CodeSheriff\CodeSheriff.csproj

  version: '{version}'

  version_prefix: '{version}'

  package_version: '{version}'

  assembly_version: '{version}'

  file_version: '{version}'

  informational_version: '{version}'

before_build:

- cmd: >-

    nuget sources Add -Name "DSharpPlus" -Source https://nuget.emzi0767.com/api/v3/index.json

    nuget restore

build:

  publish_nuget: true

  publish_nuget_symbols: true

  include_nuget_references: true

  publish_core_console: true

  verbosity: minimal